### ISSUE TITLE
Too many files

### ISSUE THREAD

**Issue by AhnJihwan** [alisinabh/paperify#10]
There is like 100 image files now. How can I make it one?

**Comment by alisinabh** [comment]
Hi @AhnJihwan,

Paperify will create qr codes for you to print and store safely. If you want to restore your file from those images, you can use the `digitallify.sh` script as you can read in the `README.md` file. Also keep in mind that each qr code can only hold exactly 2953 bytes so it may not be a good choice for large files.

Thank you.

**Comment by AhnJihwan** [comment]
Thanks a lot.
Thank you.
Maybe I will use this for small files though; it is really easy to use and is perfect, the thing what I exactly needed!

**Comment by alisinabh** [comment]
Thank you, It was nice to hear that. :)
