### ISSUE TITLE
Notes to run on OS X

### ISSUE THREAD

**Issue by apeckham** [alisinabh/paperify#11]
To run on OS X:

- `brew install coreutils qrencode zbarimg`
- change `split` to `gsplit` in `paperify.sh` line 41 because [OS X split doesn't support -d](https://apple.stackexchange.com/questions/138785/d-option-for-split-is-illegal-on-os-x-10-9/138788)

Thanks!

**Comment by alisinabh** [comment]
@apeckham Thank you very much for the notes. I will add them to the `README`

:heart:

**Comment by alisinabh** [comment]
Also I have changed that line in the #12 pull. It would be awesome if you can please check to see if it works on OS X since I currently do not have access to one. Thanks again.
