### ISSUE TITLE
./digitallify.sh: line 33: $outputfile: ambiguous redirect

### ISSUE THREAD

**Issue by manujchandra** [alisinabh/paperify#29]
Hi, 

When I use the following command I get the error below:

Using the latest download from master branch.
zbar version 0.23.90

```
./digitallify.sh out.txt CODE_OF_CONDUCT
```

```
reconstructing CODE_OF_CONDUCT.md-000.png
WARNING: decoder/databar.c:1248: _zbar_decode_databar: Assertion "seg->finder >= 0" failed.
	i=2 f=-1(000) part=1
WARNING: decoder/databar.c:1248: _zbar_decode_databar: Assertion "seg->finder >= 0" failed.
	i=3 f=-1(000) part=1
reconstructing CODE_OF_CONDUCT.md-001.png
WARNING: decoder/databar.c:1248: _zbar_decode_databar: Assertion "seg->finder >= 0" failed.
	i=2 f=-1(000) part=1
WARNING: decoder/databar.c:1248: _zbar_decode_databar: Assertion "seg->finder >= 0" failed.
	i=3 f=-1(000) part=1
000-CODE_OF_CONDUCT.md-000.chunk 001-CODE_OF_CONDUCT.md-001.chunk
./digitallify.sh: line 33: $outputfile: ambiguous redirect
```

![CODE_OF_CONDUCT md-000](https://github.com/alisinabh/paperify/assets/15191493/11018185-f894-4370-8dbd-4b3e6eb65914)
![CODE_OF_CONDUCT md-001](https://github.com/alisinabh/paperify/assets/15191493/178aa6ce-fe36-4138-9051-a1e6c68c0e71)

**Comment by alisinabh** [comment]
Hey @manujchandra,

I have pushed a new commit in master (09bd8fd81b05233140ff24a66bf5838023addf43) which should fix this. Can you try again and let me know?

**Comment by manujchandra** [comment]
Thanks. Its working now.
