### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by JackThePug** [alisinabh/paperify#3]
Upon trying to encode a file I got this error:

![image](https://user-images.githubusercontent.com/38968855/93632840-dc0bcb00-f9a2-11ea-8518-440c753ec93b.png)

**Comment by alisinabh** [comment]
Hi, I've added a commit which I think may fix this. Please try it and let me know.

**Comment by JackThePug** [comment]
Hello, It did work. Thank you!

**Comment by JackThePug** [comment]
Got this error while trying to use digitalify 
![image](https://user-images.githubusercontent.com/38968855/93686440-25bfe880-fa6b-11ea-8489-ecd69db9e4f1.png)

**Comment by alisinabh** [comment]
@JackThePug You are running it incorrectly. The first argument is the **output file name** and the second parameter is the directory of images. 

Just choose a name for your file and pass it as the first argument. For example `NewConsoleApp2.exe`

```bash
./digitallify.sh NewConsoleApp2.exe ConsoleApp2.exe-qr
```

This will create `NewConsoleApp2.exe` from those images inside `ConsoleApp2.exe-qr` directory.
BTW you can run `./digitallify.sh -h` for a small help. :)

Thanks.
