### ISSUE TITLE
Can't paperify/digitallify file with space

### ISSUE THREAD

**Issue by rany2** [alisinabh/paperify#6]
Files with spaces count as if they are another file.

```
user@debian/d/shm> paperify a\ a
/home/user/.local/bin/paperify: line 6: [: too many arguments
/home/user/.local/bin/paperify: line 9: [: too many arguments
Paperifying a a
rm: cannot remove 'a': Is a directory

```

**Comment by alisinabh** [comment]
Hi @analotia,

Thanks for the report. I have fixed this issue. Please check it and report if the problem persists.

Have a great week.

**Comment by rany2** [comment]
Hi @alisinabh,

I could confirm it's fixed with paperify but the issue still exists with digitallify.

Thank you

**Comment by alisinabh** [comment]
Hi @analotia,

`digitallify.sh` should work properly now.

Thank you for the report. :heart:
